export const GET_COLLECTIONS = 'GET_COLLECTIONS'

export const GET_DATA_SOURCE = 'GET_DATA_SOURCE'
export const SET_DATA_SOURCE = 'SET_DATA_SOURCE'
export const SET_LANGUAGE = 'SET_LANGUAGE'
export const SET_LINE_DATA = 'SET_LINE_DATA'